name = "SSNVariability"
uuid = "84a636dd-e9d1-41a5-8ff3-63bcc87dbbda"
authors = ["Dylan Festa"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
